// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	SemanticScholarID pgtype.Text        `json:"semantic_scholar_id"`
	Orcid             pgtype.Text        `json:"orcid"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type EmbeddingActivationIntent struct {
	ID                  uuid.UUID          `json:"id"`
	GenerationID        uuid.UUID          `json:"generation_id"`
	TargetCollection    string             `json:"target_collection"`
	AliasName           string             `json:"alias_name"`
	PreviousCollection  pgtype.Text        `json:"previous_collection"`
	Status              string             `json:"status"`
	Attempts            int32              `json:"attempts"`
	LastError           pgtype.Text        `json:"last_error"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	CompletedAt         pgtype.Timestamptz `json:"completed_at"`
	ExpectedPointCount  pgtype.Int8        `json:"expected_point_count"`
	ChunkSnapshotDigest pgtype.Text        `json:"chunk_snapshot_digest"`
}

type EmbeddingCleanupTask struct {
	ID             uuid.UUID          `json:"id"`
	CollectionName string             `json:"collection_name"`
	PointID        uuid.UUID          `json:"point_id"`
	TopicID        uuid.UUID          `json:"topic_id"`
	PaperID        uuid.UUID          `json:"paper_id"`
	ChunkID        pgtype.UUID        `json:"chunk_id"`
	Reason         string             `json:"reason"`
	Status         string             `json:"status"`
	Attempts       int32              `json:"attempts"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

type EmbeddingGeneration struct {
	ID                 uuid.UUID          `json:"id"`
	Provider           string             `json:"provider"`
	Model              string             `json:"model"`
	Dimensions         int32              `json:"dimensions"`
	InstructionVersion string             `json:"instruction_version"`
	IndexingVersion    string             `json:"indexing_version"`
	CollectionName     string             `json:"collection_name"`
	Status             string             `json:"status"`
	IndexedChunks      int64              `json:"indexed_chunks"`
	ErrorMessage       pgtype.Text        `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ActivatedAt        pgtype.Timestamptz `json:"activated_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type NovelDirection struct {
	ID                       uuid.UUID          `json:"id"`
	TopicID                  uuid.UUID          `json:"topic_id"`
	GapID                    pgtype.UUID        `json:"gap_id"`
	Title                    string             `json:"title"`
	Description              pgtype.Text        `json:"description"`
	Rationale                pgtype.Text        `json:"rationale"`
	FeasibilityScore         pgtype.Float8      `json:"feasibility_score"`
	ImplementationComplexity pgtype.Text        `json:"implementation_complexity"`
	EstimatedCost            pgtype.Text        `json:"estimated_cost"`
	IndustryViability        pgtype.Text        `json:"industry_viability"`
	TimeToMvp                pgtype.Text        `json:"time_to_mvp"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type Paper struct {
	ID              uuid.UUID          `json:"id"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	SourceUrl       pgtype.Text        `json:"source_url"`
	Title           string             `json:"title"`
	Abstract        pgtype.Text        `json:"abstract"`
	PublicationDate pgtype.Date        `json:"publication_date"`
	Venue           pgtype.Text        `json:"venue"`
	PdfUrl          pgtype.Text        `json:"pdf_url"`
	PdfDownloaded   pgtype.Bool        `json:"pdf_downloaded"`
	PdfParsed       pgtype.Bool        `json:"pdf_parsed"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PaperAuthor struct {
	PaperID  uuid.UUID `json:"paper_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Position int32     `json:"position"`
}

type PaperChunk struct {
	ID                          uuid.UUID          `json:"id"`
	TopicID                     uuid.UUID          `json:"topic_id"`
	PaperID                     uuid.UUID          `json:"paper_id"`
	ChunkType                   string             `json:"chunk_type"`
	ChunkIndex                  int32              `json:"chunk_index"`
	Text                        string             `json:"text"`
	ContentHash                 string             `json:"content_hash"`
	Source                      string             `json:"source"`
	EmbeddingStatus             string             `json:"embedding_status"`
	ErrorMessage                pgtype.Text        `json:"error_message"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
	EmbeddedContentHash         pgtype.Text        `json:"embedded_content_hash"`
	SectionHeading              pgtype.Text        `json:"section_heading"`
	EmbeddingProvider           pgtype.Text        `json:"embedding_provider"`
	EmbeddingModel              pgtype.Text        `json:"embedding_model"`
	EmbeddingDimensions         pgtype.Int4        `json:"embedding_dimensions"`
	EmbeddingInstructionVersion pgtype.Text        `json:"embedding_instruction_version"`
	EmbeddingIndexingVersion    pgtype.Text        `json:"embedding_indexing_version"`
	QdrantCollection            pgtype.Text        `json:"qdrant_collection"`
	QdrantPointID               pgtype.UUID        `json:"qdrant_point_id"`
}

type PaperDocument struct {
	PaperID        uuid.UUID          `json:"paper_id"`
	PdfHash        string             `json:"pdf_hash"`
	ParserProvider string             `json:"parser_provider"`
	ParserVersion  string             `json:"parser_version"`
	Status         string             `json:"status"`
	DurationMs     int64              `json:"duration_ms"`
	Warnings       []byte             `json:"warnings"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	Markdown       pgtype.Text        `json:"markdown"`
	ParserJson     []byte             `json:"parser_json"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PipelineStageCheckpoint struct {
	ID           uuid.UUID          `json:"id"`
	RunID        uuid.UUID          `json:"run_id"`
	TopicID      uuid.UUID          `json:"topic_id"`
	Stage        string             `json:"stage"`
	Status       string             `json:"status"`
	Output       []byte             `json:"output"`
	Attempt      int32              `json:"attempt"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ResearchGap struct {
	ID              uuid.UUID          `json:"id"`
	TopicID         uuid.UUID          `json:"topic_id"`
	GapType         string             `json:"gap_type"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	RelatedPaperIds []uuid.UUID        `json:"related_paper_ids"`
	Evidence        pgtype.Text        `json:"evidence"`
	Feasibility     json.RawMessage    `json:"feasibility"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type ResearchTopic struct {
	ID              uuid.UUID          `json:"id"`
	Topic           string             `json:"topic"`
	ExpandedQueries json.RawMessage    `json:"expanded_queries"`
	Status          string             `json:"status"`
	Config          json.RawMessage    `json:"config"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	RunID           uuid.UUID          `json:"run_id"`
	CurrentStage    string             `json:"current_stage"`
	Progress        float64            `json:"progress"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
}

type TopicPaper struct {
	TopicID         uuid.UUID          `json:"topic_id"`
	PaperID         uuid.UUID          `json:"paper_id"`
	DiscoverySource string             `json:"discovery_source"`
	RelevanceScore  pgtype.Float8      `json:"relevance_score"`
	Analysis        []byte             `json:"analysis"`
	AnalysisStatus  string             `json:"analysis_status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
