// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddCitation(ctx context.Context, arg AddCitationParams) error
	AddPaperAuthor(ctx context.Context, arg AddPaperAuthorParams) error
	CountPapersByTopic(ctx context.Context, topicID uuid.UUID) (int64, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (*Author, error)
	CreateNovelDirection(ctx context.Context, arg CreateNovelDirectionParams) (*NovelDirection, error)
	CreatePaper(ctx context.Context, arg CreatePaperParams) error
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (*PipelineRun, error)
	CreateResearchGap(ctx context.Context, arg CreateResearchGapParams) (*ResearchGap, error)
	CreateResearchTopic(ctx context.Context, arg CreateResearchTopicParams) (*ResearchTopic, error)
	DeletePapersByTopic(ctx context.Context, topicID uuid.UUID) error
	DeleteResearchTopic(ctx context.Context, id uuid.UUID) error
	GetAuthorBySemanticScholarID(ctx context.Context, semanticScholarID pgtype.Text) (*Author, error)
	GetLatestPipelineRun(ctx context.Context, topicID uuid.UUID) (*PipelineRun, error)
	GetNovelDirection(ctx context.Context, id uuid.UUID) (*NovelDirection, error)
	GetNovelDirectionsByTopic(ctx context.Context, topicID uuid.UUID) ([]*NovelDirection, error)
	GetPaper(ctx context.Context, id uuid.UUID) (*Paper, error)
	GetPaperAuthors(ctx context.Context, paperID uuid.UUID) ([]*Author, error)
	GetPaperByExternalID(ctx context.Context, arg GetPaperByExternalIDParams) (*Paper, error)
	GetPaperCitations(ctx context.Context, citingPaperID uuid.UUID) ([]*Paper, error)
	GetPaperCitedBy(ctx context.Context, citedPaperID uuid.UUID) ([]*Paper, error)
	GetPapersByTopic(ctx context.Context, topicID uuid.UUID) ([]*Paper, error)
	GetPapersByTopicForAnalysis(ctx context.Context, topicID uuid.UUID) ([]*GetPapersByTopicForAnalysisRow, error)
	GetPipelineRun(ctx context.Context, id uuid.UUID) (*PipelineRun, error)
	GetPipelineRunsByTopic(ctx context.Context, topicID uuid.UUID) ([]*PipelineRun, error)
	GetResearchGap(ctx context.Context, id uuid.UUID) (*ResearchGap, error)
	GetResearchGapsByTopic(ctx context.Context, topicID uuid.UUID) ([]*ResearchGap, error)
	GetResearchTopic(ctx context.Context, id uuid.UUID) (*ResearchTopic, error)
	GetResearchTopicByStatus(ctx context.Context, status string) ([]*ResearchTopic, error)
	ListResearchTopics(ctx context.Context, arg ListResearchTopicsParams) ([]*ResearchTopic, error)
	UpdatePaperAnalysis(ctx context.Context, arg UpdatePaperAnalysisParams) error
	UpdatePaperEmbeddingStatus(ctx context.Context, arg UpdatePaperEmbeddingStatusParams) (*Paper, error)
	UpdatePaperPDFStatus(ctx context.Context, arg UpdatePaperPDFStatusParams) (*Paper, error)
	UpdatePaperRelevanceScore(ctx context.Context, arg UpdatePaperRelevanceScoreParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (*PipelineRun, error)
	UpdateResearchTopicExpandedQueries(ctx context.Context, arg UpdateResearchTopicExpandedQueriesParams) (*ResearchTopic, error)
	UpdateResearchTopicStatus(ctx context.Context, arg UpdateResearchTopicStatusParams) (*ResearchTopic, error)
}

var _ Querier = (*Queries)(nil)
