// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActivateEmbeddingGeneration(ctx context.Context, id uuid.UUID) (*EmbeddingGeneration, error)
	AddPaperAuthor(ctx context.Context, arg AddPaperAuthorParams) error
	CompleteEmbeddingActivationIntent(ctx context.Context, id uuid.UUID) (*EmbeddingActivationIntent, error)
	CompleteEmbeddingCleanupTask(ctx context.Context, id uuid.UUID) (*EmbeddingCleanupTask, error)
	CompletePaperChunkEmbedding(ctx context.Context, arg CompletePaperChunkEmbeddingParams) (*PaperChunk, error)
	CompletePipelineStage(ctx context.Context, arg CompletePipelineStageParams) (*PipelineStageCheckpoint, error)
	CountPapersByTopic(ctx context.Context, topicID uuid.UUID) (int64, error)
	CreateEmbeddingActivationIntent(ctx context.Context, arg CreateEmbeddingActivationIntentParams) (*EmbeddingActivationIntent, error)
	CreateEmbeddingCleanupTask(ctx context.Context, arg CreateEmbeddingCleanupTaskParams) (*EmbeddingCleanupTask, error)
	CreateEmbeddingGeneration(ctx context.Context, arg CreateEmbeddingGenerationParams) (*EmbeddingGeneration, error)
	CreateNovelDirection(ctx context.Context, arg CreateNovelDirectionParams) (*NovelDirection, error)
	CreatePaper(ctx context.Context, arg CreatePaperParams) (uuid.UUID, error)
	CreateResearchGap(ctx context.Context, arg CreateResearchGapParams) (*ResearchGap, error)
	CreateResearchTopic(ctx context.Context, arg CreateResearchTopicParams) (*ResearchTopic, error)
	DeletePapersByTopic(ctx context.Context, topicID uuid.UUID) error
	DeleteResearchTopic(ctx context.Context, id uuid.UUID) error
	DeleteStalePaperChunks(ctx context.Context, arg DeleteStalePaperChunksParams) ([]*PaperChunk, error)
	FailEmbeddingActivationIntent(ctx context.Context, arg FailEmbeddingActivationIntentParams) (*EmbeddingActivationIntent, error)
	FailEmbeddingCleanupTask(ctx context.Context, arg FailEmbeddingCleanupTaskParams) (*EmbeddingCleanupTask, error)
	FailEmbeddingGeneration(ctx context.Context, arg FailEmbeddingGenerationParams) (*EmbeddingGeneration, error)
	FailPipelineStage(ctx context.Context, arg FailPipelineStageParams) (*PipelineStageCheckpoint, error)
	GetActiveEmbeddingGeneration(ctx context.Context) (*EmbeddingGeneration, error)
	GetCompletedPaperChunks(ctx context.Context, arg GetCompletedPaperChunksParams) ([]*PaperChunk, error)
	GetCompletedPaperIDsByTopic(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error)
	GetEmbeddingActivationIntent(ctx context.Context, id uuid.UUID) (*EmbeddingActivationIntent, error)
	GetEmbeddingGeneration(ctx context.Context, id uuid.UUID) (*EmbeddingGeneration, error)
	GetNextPaperAuthorPosition(ctx context.Context, paperID uuid.UUID) (int32, error)
	GetNovelDirection(ctx context.Context, id uuid.UUID) (*NovelDirection, error)
	GetNovelDirectionsByTopic(ctx context.Context, topicID uuid.UUID) ([]*NovelDirection, error)
	GetPaper(ctx context.Context, id uuid.UUID) (*Paper, error)
	GetPaperAuthors(ctx context.Context, paperID uuid.UUID) ([]*Author, error)
	GetPaperByExternalID(ctx context.Context, arg GetPaperByExternalIDParams) (*Paper, error)
	GetPaperChunks(ctx context.Context, arg GetPaperChunksParams) ([]*PaperChunk, error)
	GetPaperDocument(ctx context.Context, paperID uuid.UUID) (*PaperDocument, error)
	GetPapersByTopic(ctx context.Context, topicID uuid.UUID) ([]*Paper, error)
	GetPapersByTopicForAnalysis(ctx context.Context, topicID uuid.UUID) ([]*GetPapersByTopicForAnalysisRow, error)
	GetPendingEmbeddingActivationIntent(ctx context.Context) (*EmbeddingActivationIntent, error)
	GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (*PipelineStageCheckpoint, error)
	GetPipelineStages(ctx context.Context, runID uuid.UUID) ([]*PipelineStageCheckpoint, error)
	GetResearchGap(ctx context.Context, id uuid.UUID) (*ResearchGap, error)
	GetResearchGapsByTopic(ctx context.Context, topicID uuid.UUID) ([]*ResearchGap, error)
	GetResearchTopic(ctx context.Context, id uuid.UUID) (*ResearchTopic, error)
	GetResearchTopicByStatus(ctx context.Context, status string) ([]*ResearchTopic, error)
	ListPaperChunksForReindex(ctx context.Context) ([]*PaperChunk, error)
	ListPendingEmbeddingCleanupTasks(ctx context.Context, limit int32) ([]*EmbeddingCleanupTask, error)
	ListRecoverableResearchTopics(ctx context.Context) ([]*ResearchTopic, error)
	ListResearchTopics(ctx context.Context, arg ListResearchTopicsParams) ([]*ResearchTopic, error)
	LockPaperChunksForEmbeddingActivation(ctx context.Context) error
	MarkEmbeddingActivationAliasSwitched(ctx context.Context, id uuid.UUID) (*EmbeddingActivationIntent, error)
	MarkEmbeddingGenerationReady(ctx context.Context, arg MarkEmbeddingGenerationReadyParams) (*EmbeddingGeneration, error)
	MarkPaperChunkEmbeddingIndexing(ctx context.Context, arg MarkPaperChunkEmbeddingIndexingParams) (*PaperChunk, error)
	MarkPaperChunkForActiveGeneration(ctx context.Context, arg MarkPaperChunkForActiveGenerationParams) (*PaperChunk, error)
	RetireActiveEmbeddingGenerations(ctx context.Context, id uuid.UUID) error
	StartPipelineStage(ctx context.Context, arg StartPipelineStageParams) (*PipelineStageCheckpoint, error)
	SupersedeEmbeddingActivationIntent(ctx context.Context, arg SupersedeEmbeddingActivationIntentParams) (*EmbeddingActivationIntent, error)
	UpdateEmbeddingGenerationProgress(ctx context.Context, arg UpdateEmbeddingGenerationProgressParams) (*EmbeddingGeneration, error)
	UpdatePaperAnalysis(ctx context.Context, arg UpdatePaperAnalysisParams) error
	UpdatePaperChunkEmbeddingStatus(ctx context.Context, arg UpdatePaperChunkEmbeddingStatusParams) (*PaperChunk, error)
	UpdatePaperPDFStatus(ctx context.Context, arg UpdatePaperPDFStatusParams) (*Paper, error)
	UpdatePaperRelevanceScore(ctx context.Context, arg UpdatePaperRelevanceScoreParams) error
	UpdateResearchTopicExpandedQueries(ctx context.Context, arg UpdateResearchTopicExpandedQueriesParams) (*ResearchTopic, error)
	UpdateResearchTopicState(ctx context.Context, arg UpdateResearchTopicStateParams) (*ResearchTopic, error)
	UpdateResearchTopicStatus(ctx context.Context, arg UpdateResearchTopicStatusParams) (*ResearchTopic, error)
	UpsertAuthorByName(ctx context.Context, name string) (*Author, error)
	UpsertAuthorBySemanticScholarID(ctx context.Context, arg UpsertAuthorBySemanticScholarIDParams) (*Author, error)
	UpsertPaperChunk(ctx context.Context, arg UpsertPaperChunkParams) (*PaperChunk, error)
	UpsertPaperDocument(ctx context.Context, arg UpsertPaperDocumentParams) (*PaperDocument, error)
}

var _ Querier = (*Queries)(nil)
