// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddCitation(ctx context.Context, arg AddCitationParams) error
	AddPaperAuthor(ctx context.Context, arg AddPaperAuthorParams) error
	CompletePipelineStage(ctx context.Context, arg CompletePipelineStageParams) (*PipelineStageCheckpoint, error)
	CountPapersByTopic(ctx context.Context, topicID uuid.UUID) (int64, error)
	CreateNovelDirection(ctx context.Context, arg CreateNovelDirectionParams) (*NovelDirection, error)
	CreatePaper(ctx context.Context, arg CreatePaperParams) (uuid.UUID, error)
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (*PipelineRun, error)
	CreateResearchGap(ctx context.Context, arg CreateResearchGapParams) (*ResearchGap, error)
	CreateResearchTopic(ctx context.Context, arg CreateResearchTopicParams) (*ResearchTopic, error)
	DeletePapersByTopic(ctx context.Context, topicID uuid.UUID) error
	DeleteResearchTopic(ctx context.Context, id uuid.UUID) error
	FailPipelineStage(ctx context.Context, arg FailPipelineStageParams) (*PipelineStageCheckpoint, error)
	GetCompletedPaperIDsByTopic(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error)
	GetLatestPipelineRun(ctx context.Context, topicID uuid.UUID) (*PipelineRun, error)
	GetNextPaperAuthorPosition(ctx context.Context, paperID uuid.UUID) (int32, error)
	GetNovelDirection(ctx context.Context, id uuid.UUID) (*NovelDirection, error)
	GetNovelDirectionsByTopic(ctx context.Context, topicID uuid.UUID) ([]*NovelDirection, error)
	GetPaper(ctx context.Context, id uuid.UUID) (*Paper, error)
	GetPaperAuthors(ctx context.Context, paperID uuid.UUID) ([]*Author, error)
	GetPaperByExternalID(ctx context.Context, arg GetPaperByExternalIDParams) (*Paper, error)
	GetPaperCitations(ctx context.Context, citingPaperID uuid.UUID) ([]*Paper, error)
	GetPaperCitedBy(ctx context.Context, citedPaperID uuid.UUID) ([]*Paper, error)
	GetPapersByTopic(ctx context.Context, topicID uuid.UUID) ([]*Paper, error)
	GetPapersByTopicForAnalysis(ctx context.Context, topicID uuid.UUID) ([]*GetPapersByTopicForAnalysisRow, error)
	GetPipelineRun(ctx context.Context, id uuid.UUID) (*PipelineRun, error)
	GetPipelineRunsByTopic(ctx context.Context, topicID uuid.UUID) ([]*PipelineRun, error)
	GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (*PipelineStageCheckpoint, error)
	GetPipelineStages(ctx context.Context, runID uuid.UUID) ([]*PipelineStageCheckpoint, error)
	GetResearchGap(ctx context.Context, id uuid.UUID) (*ResearchGap, error)
	GetResearchGapsByTopic(ctx context.Context, topicID uuid.UUID) ([]*ResearchGap, error)
	GetResearchTopic(ctx context.Context, id uuid.UUID) (*ResearchTopic, error)
	GetResearchTopicByStatus(ctx context.Context, status string) ([]*ResearchTopic, error)
	ListRecoverableResearchTopics(ctx context.Context) ([]*ResearchTopic, error)
	ListResearchTopics(ctx context.Context, arg ListResearchTopicsParams) ([]*ResearchTopic, error)
	StartPipelineStage(ctx context.Context, arg StartPipelineStageParams) (*PipelineStageCheckpoint, error)
	UpdatePaperAnalysis(ctx context.Context, arg UpdatePaperAnalysisParams) error
	UpdatePaperEmbeddingStatus(ctx context.Context, arg UpdatePaperEmbeddingStatusParams) (*Paper, error)
	UpdatePaperPDFStatus(ctx context.Context, arg UpdatePaperPDFStatusParams) (*Paper, error)
	UpdatePaperRelevanceScore(ctx context.Context, arg UpdatePaperRelevanceScoreParams) error
	UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (*PipelineRun, error)
	UpdateResearchTopicExpandedQueries(ctx context.Context, arg UpdateResearchTopicExpandedQueriesParams) (*ResearchTopic, error)
	UpdateResearchTopicState(ctx context.Context, arg UpdateResearchTopicStateParams) (*ResearchTopic, error)
	UpdateResearchTopicStatus(ctx context.Context, arg UpdateResearchTopicStatusParams) (*ResearchTopic, error)
	UpsertAuthorByName(ctx context.Context, name string) (*Author, error)
	UpsertAuthorBySemanticScholarID(ctx context.Context, arg UpsertAuthorBySemanticScholarIDParams) (*Author, error)
}

var _ Querier = (*Queries)(nil)
