// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCitation = `-- name: AddCitation :exec
INSERT INTO citations (citing_paper_id, cited_paper_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddCitationParams struct {
	CitingPaperID uuid.UUID `json:"citing_paper_id"`
	CitedPaperID  uuid.UUID `json:"cited_paper_id"`
}

func (q *Queries) AddCitation(ctx context.Context, arg AddCitationParams) error {
	_, err := q.db.Exec(ctx, addCitation, arg.CitingPaperID, arg.CitedPaperID)
	return err
}

const addPaperAuthor = `-- name: AddPaperAuthor :exec
INSERT INTO paper_authors (paper_id, author_id, position)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddPaperAuthorParams struct {
	PaperID  uuid.UUID `json:"paper_id"`
	AuthorID uuid.UUID `json:"author_id"`
	Position int32     `json:"position"`
}

func (q *Queries) AddPaperAuthor(ctx context.Context, arg AddPaperAuthorParams) error {
	_, err := q.db.Exec(ctx, addPaperAuthor, arg.PaperID, arg.AuthorID, arg.Position)
	return err
}

const completePipelineStage = `-- name: CompletePipelineStage :one
UPDATE pipeline_stage_checkpoints
SET status = 'completed', output = $3, completed_at = NOW(), error_message = NULL, updated_at = NOW()
WHERE run_id = $1 AND stage = $2
RETURNING id, run_id, topic_id, stage, status, output, attempt, started_at, completed_at, error_message, created_at, updated_at
`

type CompletePipelineStageParams struct {
	RunID  uuid.UUID `json:"run_id"`
	Stage  string    `json:"stage"`
	Output []byte    `json:"output"`
}

func (q *Queries) CompletePipelineStage(ctx context.Context, arg CompletePipelineStageParams) (*PipelineStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, completePipelineStage, arg.RunID, arg.Stage, arg.Output)
	var i PipelineStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.Output,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const countPapersByTopic = `-- name: CountPapersByTopic :one
SELECT COUNT(*) FROM topic_papers WHERE topic_id = $1
`

func (q *Queries) CountPapersByTopic(ctx context.Context, topicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPapersByTopic, topicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNovelDirection = `-- name: CreateNovelDirection :one
INSERT INTO novel_directions (
    topic_id, gap_id, title, description, rationale,
    feasibility_score, implementation_complexity, estimated_cost, 
    industry_viability, time_to_mvp
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (topic_id, title) DO UPDATE SET
    gap_id = EXCLUDED.gap_id,
    description = EXCLUDED.description,
    rationale = EXCLUDED.rationale,
    feasibility_score = EXCLUDED.feasibility_score,
    implementation_complexity = EXCLUDED.implementation_complexity,
    estimated_cost = EXCLUDED.estimated_cost,
    industry_viability = EXCLUDED.industry_viability,
    time_to_mvp = EXCLUDED.time_to_mvp
RETURNING id, topic_id, gap_id, title, description, rationale, feasibility_score, implementation_complexity, estimated_cost, industry_viability, time_to_mvp, created_at
`

type CreateNovelDirectionParams struct {
	TopicID                  uuid.UUID     `json:"topic_id"`
	GapID                    pgtype.UUID   `json:"gap_id"`
	Title                    string        `json:"title"`
	Description              pgtype.Text   `json:"description"`
	Rationale                pgtype.Text   `json:"rationale"`
	FeasibilityScore         pgtype.Float8 `json:"feasibility_score"`
	ImplementationComplexity pgtype.Text   `json:"implementation_complexity"`
	EstimatedCost            pgtype.Text   `json:"estimated_cost"`
	IndustryViability        pgtype.Text   `json:"industry_viability"`
	TimeToMvp                pgtype.Text   `json:"time_to_mvp"`
}

func (q *Queries) CreateNovelDirection(ctx context.Context, arg CreateNovelDirectionParams) (*NovelDirection, error) {
	row := q.db.QueryRow(ctx, createNovelDirection,
		arg.TopicID,
		arg.GapID,
		arg.Title,
		arg.Description,
		arg.Rationale,
		arg.FeasibilityScore,
		arg.ImplementationComplexity,
		arg.EstimatedCost,
		arg.IndustryViability,
		arg.TimeToMvp,
	)
	var i NovelDirection
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.GapID,
		&i.Title,
		&i.Description,
		&i.Rationale,
		&i.FeasibilityScore,
		&i.ImplementationComplexity,
		&i.EstimatedCost,
		&i.IndustryViability,
		&i.TimeToMvp,
		&i.CreatedAt,
	)
	return &i, err
}

const createPaper = `-- name: CreatePaper :one
WITH paper AS (
    INSERT INTO papers (
        source, external_id, source_url, title, abstract,
        publication_date, venue, pdf_url
    )
    VALUES ($2, $3, $4, $5, $6, $7, $8, $9)
    ON CONFLICT (source, external_id) DO UPDATE SET
        title = EXCLUDED.title,
        abstract = EXCLUDED.abstract,
        source_url = EXCLUDED.source_url,
        publication_date = EXCLUDED.publication_date,
        venue = EXCLUDED.venue,
        pdf_url = EXCLUDED.pdf_url,
        updated_at = NOW()
    RETURNING id
)
INSERT INTO topic_papers (topic_id, paper_id, discovery_source)
SELECT $1, id, $2
FROM paper
ON CONFLICT (topic_id, paper_id) DO UPDATE SET
    discovery_source = EXCLUDED.discovery_source,
    updated_at = NOW()
RETURNING paper_id
`

type CreatePaperParams struct {
	TopicID         uuid.UUID   `json:"topic_id"`
	DiscoverySource string      `json:"discovery_source"`
	ExternalID      string      `json:"external_id"`
	SourceUrl       pgtype.Text `json:"source_url"`
	Title           string      `json:"title"`
	Abstract        pgtype.Text `json:"abstract"`
	PublicationDate pgtype.Date `json:"publication_date"`
	Venue           pgtype.Text `json:"venue"`
	PdfUrl          pgtype.Text `json:"pdf_url"`
}

func (q *Queries) CreatePaper(ctx context.Context, arg CreatePaperParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPaper,
		arg.TopicID,
		arg.DiscoverySource,
		arg.ExternalID,
		arg.SourceUrl,
		arg.Title,
		arg.Abstract,
		arg.PublicationDate,
		arg.Venue,
		arg.PdfUrl,
	)
	var paper_id uuid.UUID
	err := row.Scan(&paper_id)
	return paper_id, err
}

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs (topic_id, stage, status)
VALUES ($1, $2, $3)
RETURNING id, topic_id, stage, status, started_at, completed_at, error_message, metrics
`

type CreatePipelineRunParams struct {
	TopicID uuid.UUID `json:"topic_id"`
	Stage   string    `json:"stage"`
	Status  string    `json:"status"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (*PipelineRun, error) {
	row := q.db.QueryRow(ctx, createPipelineRun, arg.TopicID, arg.Stage, arg.Status)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metrics,
	)
	return &i, err
}

const createResearchGap = `-- name: CreateResearchGap :one
INSERT INTO research_gaps (topic_id, gap_type, title, description, related_paper_ids, evidence, feasibility)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (topic_id, title) DO UPDATE SET
    gap_type = EXCLUDED.gap_type,
    description = EXCLUDED.description,
    related_paper_ids = EXCLUDED.related_paper_ids,
    evidence = EXCLUDED.evidence,
    feasibility = EXCLUDED.feasibility
RETURNING id, topic_id, gap_type, title, description, related_paper_ids, evidence, feasibility, created_at
`

type CreateResearchGapParams struct {
	TopicID         uuid.UUID       `json:"topic_id"`
	GapType         string          `json:"gap_type"`
	Title           string          `json:"title"`
	Description     pgtype.Text     `json:"description"`
	RelatedPaperIds []uuid.UUID     `json:"related_paper_ids"`
	Evidence        pgtype.Text     `json:"evidence"`
	Feasibility     json.RawMessage `json:"feasibility"`
}

func (q *Queries) CreateResearchGap(ctx context.Context, arg CreateResearchGapParams) (*ResearchGap, error) {
	row := q.db.QueryRow(ctx, createResearchGap,
		arg.TopicID,
		arg.GapType,
		arg.Title,
		arg.Description,
		arg.RelatedPaperIds,
		arg.Evidence,
		arg.Feasibility,
	)
	var i ResearchGap
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.GapType,
		&i.Title,
		&i.Description,
		&i.RelatedPaperIds,
		&i.Evidence,
		&i.Feasibility,
		&i.CreatedAt,
	)
	return &i, err
}

const createResearchTopic = `-- name: CreateResearchTopic :one
INSERT INTO research_topics (topic, expanded_queries, status, config)
VALUES ($1, $2, $3, $4)
RETURNING id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message
`

type CreateResearchTopicParams struct {
	Topic           string          `json:"topic"`
	ExpandedQueries json.RawMessage `json:"expanded_queries"`
	Status          string          `json:"status"`
	Config          json.RawMessage `json:"config"`
}

func (q *Queries) CreateResearchTopic(ctx context.Context, arg CreateResearchTopicParams) (*ResearchTopic, error) {
	row := q.db.QueryRow(ctx, createResearchTopic,
		arg.Topic,
		arg.ExpandedQueries,
		arg.Status,
		arg.Config,
	)
	var i ResearchTopic
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ExpandedQueries,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RunID,
		&i.CurrentStage,
		&i.Progress,
		&i.ErrorMessage,
	)
	return &i, err
}

const deletePapersByTopic = `-- name: DeletePapersByTopic :exec
WITH removed AS (
    DELETE FROM topic_papers
    WHERE topic_papers.topic_id = $1
    RETURNING paper_id
)
DELETE FROM papers p
USING removed r
WHERE p.id = r.paper_id
  AND NOT EXISTS (
      SELECT 1 FROM topic_papers tp WHERE tp.paper_id = p.id
  )
`

func (q *Queries) DeletePapersByTopic(ctx context.Context, topicID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePapersByTopic, topicID)
	return err
}

const deleteResearchTopic = `-- name: DeleteResearchTopic :exec
DELETE FROM research_topics WHERE id = $1
`

func (q *Queries) DeleteResearchTopic(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResearchTopic, id)
	return err
}

const deleteStalePaperChunks = `-- name: DeleteStalePaperChunks :many
DELETE FROM paper_chunks
WHERE topic_id = $1
  AND paper_id = $2
  AND chunk_type = $3
  AND chunk_index >= $4
RETURNING id, topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source, embedding_status, error_message, created_at, updated_at
`

type DeleteStalePaperChunksParams struct {
	TopicID    uuid.UUID `json:"topic_id"`
	PaperID    uuid.UUID `json:"paper_id"`
	ChunkType  string    `json:"chunk_type"`
	ChunkIndex int32     `json:"chunk_index"`
}

func (q *Queries) DeleteStalePaperChunks(ctx context.Context, arg DeleteStalePaperChunksParams) ([]*PaperChunk, error) {
	rows, err := q.db.Query(ctx, deleteStalePaperChunks,
		arg.TopicID,
		arg.PaperID,
		arg.ChunkType,
		arg.ChunkIndex,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.PaperID,
			&i.ChunkType,
			&i.ChunkIndex,
			&i.Text,
			&i.ContentHash,
			&i.Source,
			&i.EmbeddingStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failPipelineStage = `-- name: FailPipelineStage :one
UPDATE pipeline_stage_checkpoints
SET status = 'failed', error_message = $3, updated_at = NOW()
WHERE run_id = $1 AND stage = $2
RETURNING id, run_id, topic_id, stage, status, output, attempt, started_at, completed_at, error_message, created_at, updated_at
`

type FailPipelineStageParams struct {
	RunID        uuid.UUID   `json:"run_id"`
	Stage        string      `json:"stage"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailPipelineStage(ctx context.Context, arg FailPipelineStageParams) (*PipelineStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, failPipelineStage, arg.RunID, arg.Stage, arg.ErrorMessage)
	var i PipelineStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.Output,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getCompletedPaperChunks = `-- name: GetCompletedPaperChunks :many
SELECT id, topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source, embedding_status, error_message, created_at, updated_at FROM paper_chunks
WHERE topic_id = $1
  AND paper_id = $2
  AND embedding_status = 'completed'
ORDER BY chunk_type, chunk_index
`

type GetCompletedPaperChunksParams struct {
	TopicID uuid.UUID `json:"topic_id"`
	PaperID uuid.UUID `json:"paper_id"`
}

func (q *Queries) GetCompletedPaperChunks(ctx context.Context, arg GetCompletedPaperChunksParams) ([]*PaperChunk, error) {
	rows, err := q.db.Query(ctx, getCompletedPaperChunks, arg.TopicID, arg.PaperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.PaperID,
			&i.ChunkType,
			&i.ChunkIndex,
			&i.Text,
			&i.ContentHash,
			&i.Source,
			&i.EmbeddingStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletedPaperIDsByTopic = `-- name: GetCompletedPaperIDsByTopic :many
SELECT paper_id FROM topic_papers
WHERE topic_id = $1 AND analysis_status = 'completed'
`

func (q *Queries) GetCompletedPaperIDsByTopic(ctx context.Context, topicID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getCompletedPaperIDsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var paper_id uuid.UUID
		if err := rows.Scan(&paper_id); err != nil {
			return nil, err
		}
		items = append(items, paper_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestPipelineRun = `-- name: GetLatestPipelineRun :one
SELECT id, topic_id, stage, status, started_at, completed_at, error_message, metrics FROM pipeline_runs 
WHERE topic_id = $1 
ORDER BY started_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestPipelineRun(ctx context.Context, topicID uuid.UUID) (*PipelineRun, error) {
	row := q.db.QueryRow(ctx, getLatestPipelineRun, topicID)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metrics,
	)
	return &i, err
}

const getNextPaperAuthorPosition = `-- name: GetNextPaperAuthorPosition :one
SELECT COALESCE(MAX(position) + 1, 0)::int
FROM paper_authors
WHERE paper_id = $1
`

func (q *Queries) GetNextPaperAuthorPosition(ctx context.Context, paperID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextPaperAuthorPosition, paperID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getNovelDirection = `-- name: GetNovelDirection :one
SELECT id, topic_id, gap_id, title, description, rationale, feasibility_score, implementation_complexity, estimated_cost, industry_viability, time_to_mvp, created_at FROM novel_directions WHERE id = $1
`

func (q *Queries) GetNovelDirection(ctx context.Context, id uuid.UUID) (*NovelDirection, error) {
	row := q.db.QueryRow(ctx, getNovelDirection, id)
	var i NovelDirection
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.GapID,
		&i.Title,
		&i.Description,
		&i.Rationale,
		&i.FeasibilityScore,
		&i.ImplementationComplexity,
		&i.EstimatedCost,
		&i.IndustryViability,
		&i.TimeToMvp,
		&i.CreatedAt,
	)
	return &i, err
}

const getNovelDirectionsByTopic = `-- name: GetNovelDirectionsByTopic :many
SELECT id, topic_id, gap_id, title, description, rationale, feasibility_score, implementation_complexity, estimated_cost, industry_viability, time_to_mvp, created_at FROM novel_directions WHERE topic_id = $1 ORDER BY feasibility_score DESC NULLS LAST
`

func (q *Queries) GetNovelDirectionsByTopic(ctx context.Context, topicID uuid.UUID) ([]*NovelDirection, error) {
	rows, err := q.db.Query(ctx, getNovelDirectionsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*NovelDirection{}
	for rows.Next() {
		var i NovelDirection
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.GapID,
			&i.Title,
			&i.Description,
			&i.Rationale,
			&i.FeasibilityScore,
			&i.ImplementationComplexity,
			&i.EstimatedCost,
			&i.IndustryViability,
			&i.TimeToMvp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaper = `-- name: GetPaper :one
SELECT id, source, external_id, source_url, title, abstract, publication_date, venue, embedding_status, pdf_url, pdf_downloaded, pdf_parsed, created_at, updated_at FROM papers WHERE id = $1
`

func (q *Queries) GetPaper(ctx context.Context, id uuid.UUID) (*Paper, error) {
	row := q.db.QueryRow(ctx, getPaper, id)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.Title,
		&i.Abstract,
		&i.PublicationDate,
		&i.Venue,
		&i.EmbeddingStatus,
		&i.PdfUrl,
		&i.PdfDownloaded,
		&i.PdfParsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaperAuthors = `-- name: GetPaperAuthors :many
SELECT a.id, a.name, a.semantic_scholar_id, a.orcid, a.created_at FROM authors a
JOIN paper_authors pa ON a.id = pa.author_id
WHERE pa.paper_id = $1
ORDER BY pa.position
`

func (q *Queries) GetPaperAuthors(ctx context.Context, paperID uuid.UUID) ([]*Author, error) {
	rows, err := q.db.Query(ctx, getPaperAuthors, paperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SemanticScholarID,
			&i.Orcid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaperByExternalID = `-- name: GetPaperByExternalID :one
SELECT id, source, external_id, source_url, title, abstract, publication_date, venue, embedding_status, pdf_url, pdf_downloaded, pdf_parsed, created_at, updated_at FROM papers WHERE source = $1 AND external_id = $2
`

type GetPaperByExternalIDParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetPaperByExternalID(ctx context.Context, arg GetPaperByExternalIDParams) (*Paper, error) {
	row := q.db.QueryRow(ctx, getPaperByExternalID, arg.Source, arg.ExternalID)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.Title,
		&i.Abstract,
		&i.PublicationDate,
		&i.Venue,
		&i.EmbeddingStatus,
		&i.PdfUrl,
		&i.PdfDownloaded,
		&i.PdfParsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPaperChunks = `-- name: GetPaperChunks :many
SELECT id, topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source, embedding_status, error_message, created_at, updated_at FROM paper_chunks
WHERE topic_id = $1 AND paper_id = $2
ORDER BY chunk_type, chunk_index
`

type GetPaperChunksParams struct {
	TopicID uuid.UUID `json:"topic_id"`
	PaperID uuid.UUID `json:"paper_id"`
}

func (q *Queries) GetPaperChunks(ctx context.Context, arg GetPaperChunksParams) ([]*PaperChunk, error) {
	rows, err := q.db.Query(ctx, getPaperChunks, arg.TopicID, arg.PaperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PaperChunk{}
	for rows.Next() {
		var i PaperChunk
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.PaperID,
			&i.ChunkType,
			&i.ChunkIndex,
			&i.Text,
			&i.ContentHash,
			&i.Source,
			&i.EmbeddingStatus,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaperCitations = `-- name: GetPaperCitations :many
SELECT p.id, p.source, p.external_id, p.source_url, p.title, p.abstract, p.publication_date, p.venue, p.embedding_status, p.pdf_url, p.pdf_downloaded, p.pdf_parsed, p.created_at, p.updated_at FROM papers p
JOIN citations c ON p.id = c.cited_paper_id
WHERE c.citing_paper_id = $1
`

func (q *Queries) GetPaperCitations(ctx context.Context, citingPaperID uuid.UUID) ([]*Paper, error) {
	rows, err := q.db.Query(ctx, getPaperCitations, citingPaperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.Title,
			&i.Abstract,
			&i.PublicationDate,
			&i.Venue,
			&i.EmbeddingStatus,
			&i.PdfUrl,
			&i.PdfDownloaded,
			&i.PdfParsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaperCitedBy = `-- name: GetPaperCitedBy :many
SELECT p.id, p.source, p.external_id, p.source_url, p.title, p.abstract, p.publication_date, p.venue, p.embedding_status, p.pdf_url, p.pdf_downloaded, p.pdf_parsed, p.created_at, p.updated_at FROM papers p
JOIN citations c ON p.id = c.citing_paper_id
WHERE c.cited_paper_id = $1
`

func (q *Queries) GetPaperCitedBy(ctx context.Context, citedPaperID uuid.UUID) ([]*Paper, error) {
	rows, err := q.db.Query(ctx, getPaperCitedBy, citedPaperID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.Title,
			&i.Abstract,
			&i.PublicationDate,
			&i.Venue,
			&i.EmbeddingStatus,
			&i.PdfUrl,
			&i.PdfDownloaded,
			&i.PdfParsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPapersByTopic = `-- name: GetPapersByTopic :many
SELECT p.id, p.source, p.external_id, p.source_url, p.title, p.abstract, p.publication_date, p.venue, p.embedding_status, p.pdf_url, p.pdf_downloaded, p.pdf_parsed, p.created_at, p.updated_at FROM papers p
JOIN topic_papers tp ON tp.paper_id = p.id
WHERE tp.topic_id = $1
ORDER BY tp.relevance_score DESC NULLS LAST
`

func (q *Queries) GetPapersByTopic(ctx context.Context, topicID uuid.UUID) ([]*Paper, error) {
	rows, err := q.db.Query(ctx, getPapersByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Paper{}
	for rows.Next() {
		var i Paper
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.Title,
			&i.Abstract,
			&i.PublicationDate,
			&i.Venue,
			&i.EmbeddingStatus,
			&i.PdfUrl,
			&i.PdfDownloaded,
			&i.PdfParsed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPapersByTopicForAnalysis = `-- name: GetPapersByTopicForAnalysis :many
SELECT p.id, p.source, p.external_id, p.source_url, p.title, p.abstract, p.publication_date, p.venue, p.embedding_status, p.pdf_url, p.pdf_downloaded, p.pdf_parsed, p.created_at, p.updated_at,
       tp.analysis AS topic_analysis,
       tp.relevance_score AS topic_relevance_score,
       ARRAY(
           SELECT a.name
           FROM paper_authors pa
           JOIN authors a ON a.id = pa.author_id
           WHERE pa.paper_id = p.id
           ORDER BY pa.position
       )::text[] AS authors
FROM papers p
JOIN topic_papers tp ON tp.paper_id = p.id
WHERE tp.topic_id = $1 AND tp.analysis IS NOT NULL
ORDER BY tp.relevance_score DESC NULLS LAST
`

type GetPapersByTopicForAnalysisRow struct {
	ID                  uuid.UUID          `json:"id"`
	Source              string             `json:"source"`
	ExternalID          string             `json:"external_id"`
	SourceUrl           pgtype.Text        `json:"source_url"`
	Title               string             `json:"title"`
	Abstract            pgtype.Text        `json:"abstract"`
	PublicationDate     pgtype.Date        `json:"publication_date"`
	Venue               pgtype.Text        `json:"venue"`
	EmbeddingStatus     pgtype.Text        `json:"embedding_status"`
	PdfUrl              pgtype.Text        `json:"pdf_url"`
	PdfDownloaded       pgtype.Bool        `json:"pdf_downloaded"`
	PdfParsed           pgtype.Bool        `json:"pdf_parsed"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TopicAnalysis       []byte             `json:"topic_analysis"`
	TopicRelevanceScore pgtype.Float8      `json:"topic_relevance_score"`
	Authors             []string           `json:"authors"`
}

func (q *Queries) GetPapersByTopicForAnalysis(ctx context.Context, topicID uuid.UUID) ([]*GetPapersByTopicForAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getPapersByTopicForAnalysis, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPapersByTopicForAnalysisRow{}
	for rows.Next() {
		var i GetPapersByTopicForAnalysisRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.SourceUrl,
			&i.Title,
			&i.Abstract,
			&i.PublicationDate,
			&i.Venue,
			&i.EmbeddingStatus,
			&i.PdfUrl,
			&i.PdfDownloaded,
			&i.PdfParsed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TopicAnalysis,
			&i.TopicRelevanceScore,
			&i.Authors,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineRun = `-- name: GetPipelineRun :one
SELECT id, topic_id, stage, status, started_at, completed_at, error_message, metrics FROM pipeline_runs WHERE id = $1
`

func (q *Queries) GetPipelineRun(ctx context.Context, id uuid.UUID) (*PipelineRun, error) {
	row := q.db.QueryRow(ctx, getPipelineRun, id)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metrics,
	)
	return &i, err
}

const getPipelineRunsByTopic = `-- name: GetPipelineRunsByTopic :many
SELECT id, topic_id, stage, status, started_at, completed_at, error_message, metrics FROM pipeline_runs WHERE topic_id = $1 ORDER BY started_at
`

func (q *Queries) GetPipelineRunsByTopic(ctx context.Context, topicID uuid.UUID) ([]*PipelineRun, error) {
	rows, err := q.db.Query(ctx, getPipelineRunsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PipelineRun{}
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Stage,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.Metrics,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPipelineStage = `-- name: GetPipelineStage :one
SELECT id, run_id, topic_id, stage, status, output, attempt, started_at, completed_at, error_message, created_at, updated_at FROM pipeline_stage_checkpoints
WHERE run_id = $1 AND stage = $2
`

type GetPipelineStageParams struct {
	RunID uuid.UUID `json:"run_id"`
	Stage string    `json:"stage"`
}

func (q *Queries) GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (*PipelineStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, getPipelineStage, arg.RunID, arg.Stage)
	var i PipelineStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.Output,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getPipelineStages = `-- name: GetPipelineStages :many
SELECT id, run_id, topic_id, stage, status, output, attempt, started_at, completed_at, error_message, created_at, updated_at FROM pipeline_stage_checkpoints
WHERE run_id = $1 ORDER BY started_at
`

func (q *Queries) GetPipelineStages(ctx context.Context, runID uuid.UUID) ([]*PipelineStageCheckpoint, error) {
	rows, err := q.db.Query(ctx, getPipelineStages, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*PipelineStageCheckpoint{}
	for rows.Next() {
		var i PipelineStageCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.TopicID,
			&i.Stage,
			&i.Status,
			&i.Output,
			&i.Attempt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResearchGap = `-- name: GetResearchGap :one
SELECT id, topic_id, gap_type, title, description, related_paper_ids, evidence, feasibility, created_at FROM research_gaps WHERE id = $1
`

func (q *Queries) GetResearchGap(ctx context.Context, id uuid.UUID) (*ResearchGap, error) {
	row := q.db.QueryRow(ctx, getResearchGap, id)
	var i ResearchGap
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.GapType,
		&i.Title,
		&i.Description,
		&i.RelatedPaperIds,
		&i.Evidence,
		&i.Feasibility,
		&i.CreatedAt,
	)
	return &i, err
}

const getResearchGapsByTopic = `-- name: GetResearchGapsByTopic :many
SELECT id, topic_id, gap_type, title, description, related_paper_ids, evidence, feasibility, created_at FROM research_gaps WHERE topic_id = $1 ORDER BY created_at
`

func (q *Queries) GetResearchGapsByTopic(ctx context.Context, topicID uuid.UUID) ([]*ResearchGap, error) {
	rows, err := q.db.Query(ctx, getResearchGapsByTopic, topicID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ResearchGap{}
	for rows.Next() {
		var i ResearchGap
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.GapType,
			&i.Title,
			&i.Description,
			&i.RelatedPaperIds,
			&i.Evidence,
			&i.Feasibility,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResearchTopic = `-- name: GetResearchTopic :one
SELECT id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message FROM research_topics WHERE id = $1
`

func (q *Queries) GetResearchTopic(ctx context.Context, id uuid.UUID) (*ResearchTopic, error) {
	row := q.db.QueryRow(ctx, getResearchTopic, id)
	var i ResearchTopic
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ExpandedQueries,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RunID,
		&i.CurrentStage,
		&i.Progress,
		&i.ErrorMessage,
	)
	return &i, err
}

const getResearchTopicByStatus = `-- name: GetResearchTopicByStatus :many
SELECT id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message FROM research_topics WHERE status = $1 ORDER BY created_at DESC
`

func (q *Queries) GetResearchTopicByStatus(ctx context.Context, status string) ([]*ResearchTopic, error) {
	rows, err := q.db.Query(ctx, getResearchTopicByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ResearchTopic{}
	for rows.Next() {
		var i ResearchTopic
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ExpandedQueries,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RunID,
			&i.CurrentStage,
			&i.Progress,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverableResearchTopics = `-- name: ListRecoverableResearchTopics :many
SELECT id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message FROM research_topics
WHERE status NOT IN ('completed', 'failed')
ORDER BY created_at
`

func (q *Queries) ListRecoverableResearchTopics(ctx context.Context) ([]*ResearchTopic, error) {
	rows, err := q.db.Query(ctx, listRecoverableResearchTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ResearchTopic{}
	for rows.Next() {
		var i ResearchTopic
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ExpandedQueries,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RunID,
			&i.CurrentStage,
			&i.Progress,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResearchTopics = `-- name: ListResearchTopics :many
SELECT id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message FROM research_topics ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListResearchTopicsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResearchTopics(ctx context.Context, arg ListResearchTopicsParams) ([]*ResearchTopic, error) {
	rows, err := q.db.Query(ctx, listResearchTopics, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ResearchTopic{}
	for rows.Next() {
		var i ResearchTopic
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.ExpandedQueries,
			&i.Status,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.RunID,
			&i.CurrentStage,
			&i.Progress,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startPipelineStage = `-- name: StartPipelineStage :one
INSERT INTO pipeline_stage_checkpoints (run_id, topic_id, stage, status, attempt, started_at, completed_at, error_message)
VALUES ($1, $2, $3, 'running', 1, NOW(), NULL, NULL)
ON CONFLICT (run_id, stage) DO UPDATE SET
    status = 'running',
    attempt = pipeline_stage_checkpoints.attempt + 1,
    started_at = NOW(),
    completed_at = NULL,
    error_message = NULL,
    updated_at = NOW()
RETURNING id, run_id, topic_id, stage, status, output, attempt, started_at, completed_at, error_message, created_at, updated_at
`

type StartPipelineStageParams struct {
	RunID   uuid.UUID `json:"run_id"`
	TopicID uuid.UUID `json:"topic_id"`
	Stage   string    `json:"stage"`
}

func (q *Queries) StartPipelineStage(ctx context.Context, arg StartPipelineStageParams) (*PipelineStageCheckpoint, error) {
	row := q.db.QueryRow(ctx, startPipelineStage, arg.RunID, arg.TopicID, arg.Stage)
	var i PipelineStageCheckpoint
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.Output,
		&i.Attempt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePaperAnalysis = `-- name: UpdatePaperAnalysis :exec
UPDATE topic_papers
SET analysis = $3, analysis_status = 'completed', updated_at = NOW()
WHERE topic_id = $1 AND paper_id = $2
`

type UpdatePaperAnalysisParams struct {
	TopicID  uuid.UUID `json:"topic_id"`
	PaperID  uuid.UUID `json:"paper_id"`
	Analysis []byte    `json:"analysis"`
}

func (q *Queries) UpdatePaperAnalysis(ctx context.Context, arg UpdatePaperAnalysisParams) error {
	_, err := q.db.Exec(ctx, updatePaperAnalysis, arg.TopicID, arg.PaperID, arg.Analysis)
	return err
}

const updatePaperChunkEmbeddingStatus = `-- name: UpdatePaperChunkEmbeddingStatus :one
UPDATE paper_chunks
SET embedding_status = $3,
    error_message = $4,
    updated_at = NOW()
WHERE topic_id = $1 AND id = $2
RETURNING id, topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source, embedding_status, error_message, created_at, updated_at
`

type UpdatePaperChunkEmbeddingStatusParams struct {
	TopicID         uuid.UUID   `json:"topic_id"`
	ID              uuid.UUID   `json:"id"`
	EmbeddingStatus string      `json:"embedding_status"`
	ErrorMessage    pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdatePaperChunkEmbeddingStatus(ctx context.Context, arg UpdatePaperChunkEmbeddingStatusParams) (*PaperChunk, error) {
	row := q.db.QueryRow(ctx, updatePaperChunkEmbeddingStatus,
		arg.TopicID,
		arg.ID,
		arg.EmbeddingStatus,
		arg.ErrorMessage,
	)
	var i PaperChunk
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PaperID,
		&i.ChunkType,
		&i.ChunkIndex,
		&i.Text,
		&i.ContentHash,
		&i.Source,
		&i.EmbeddingStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePaperEmbeddingStatus = `-- name: UpdatePaperEmbeddingStatus :one
UPDATE papers 
SET embedding_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, source, external_id, source_url, title, abstract, publication_date, venue, embedding_status, pdf_url, pdf_downloaded, pdf_parsed, created_at, updated_at
`

type UpdatePaperEmbeddingStatusParams struct {
	ID              uuid.UUID   `json:"id"`
	EmbeddingStatus pgtype.Text `json:"embedding_status"`
}

func (q *Queries) UpdatePaperEmbeddingStatus(ctx context.Context, arg UpdatePaperEmbeddingStatusParams) (*Paper, error) {
	row := q.db.QueryRow(ctx, updatePaperEmbeddingStatus, arg.ID, arg.EmbeddingStatus)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.Title,
		&i.Abstract,
		&i.PublicationDate,
		&i.Venue,
		&i.EmbeddingStatus,
		&i.PdfUrl,
		&i.PdfDownloaded,
		&i.PdfParsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePaperPDFStatus = `-- name: UpdatePaperPDFStatus :one
UPDATE papers 
SET pdf_downloaded = $2, pdf_parsed = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, source, external_id, source_url, title, abstract, publication_date, venue, embedding_status, pdf_url, pdf_downloaded, pdf_parsed, created_at, updated_at
`

type UpdatePaperPDFStatusParams struct {
	ID            uuid.UUID   `json:"id"`
	PdfDownloaded pgtype.Bool `json:"pdf_downloaded"`
	PdfParsed     pgtype.Bool `json:"pdf_parsed"`
}

func (q *Queries) UpdatePaperPDFStatus(ctx context.Context, arg UpdatePaperPDFStatusParams) (*Paper, error) {
	row := q.db.QueryRow(ctx, updatePaperPDFStatus, arg.ID, arg.PdfDownloaded, arg.PdfParsed)
	var i Paper
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.SourceUrl,
		&i.Title,
		&i.Abstract,
		&i.PublicationDate,
		&i.Venue,
		&i.EmbeddingStatus,
		&i.PdfUrl,
		&i.PdfDownloaded,
		&i.PdfParsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updatePaperRelevanceScore = `-- name: UpdatePaperRelevanceScore :exec
UPDATE topic_papers
SET relevance_score = $3, updated_at = NOW()
WHERE topic_id = $1 AND paper_id = $2
`

type UpdatePaperRelevanceScoreParams struct {
	TopicID        uuid.UUID     `json:"topic_id"`
	PaperID        uuid.UUID     `json:"paper_id"`
	RelevanceScore pgtype.Float8 `json:"relevance_score"`
}

func (q *Queries) UpdatePaperRelevanceScore(ctx context.Context, arg UpdatePaperRelevanceScoreParams) error {
	_, err := q.db.Exec(ctx, updatePaperRelevanceScore, arg.TopicID, arg.PaperID, arg.RelevanceScore)
	return err
}

const updatePipelineRunStatus = `-- name: UpdatePipelineRunStatus :one
UPDATE pipeline_runs 
SET status = $2, completed_at = $3, error_message = $4, metrics = $5
WHERE id = $1
RETURNING id, topic_id, stage, status, started_at, completed_at, error_message, metrics
`

type UpdatePipelineRunStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	Metrics      json.RawMessage    `json:"metrics"`
}

func (q *Queries) UpdatePipelineRunStatus(ctx context.Context, arg UpdatePipelineRunStatusParams) (*PipelineRun, error) {
	row := q.db.QueryRow(ctx, updatePipelineRunStatus,
		arg.ID,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.Metrics,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Stage,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
		&i.Metrics,
	)
	return &i, err
}

const updateResearchTopicExpandedQueries = `-- name: UpdateResearchTopicExpandedQueries :one
UPDATE research_topics 
SET expanded_queries = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message
`

type UpdateResearchTopicExpandedQueriesParams struct {
	ID              uuid.UUID       `json:"id"`
	ExpandedQueries json.RawMessage `json:"expanded_queries"`
}

func (q *Queries) UpdateResearchTopicExpandedQueries(ctx context.Context, arg UpdateResearchTopicExpandedQueriesParams) (*ResearchTopic, error) {
	row := q.db.QueryRow(ctx, updateResearchTopicExpandedQueries, arg.ID, arg.ExpandedQueries)
	var i ResearchTopic
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ExpandedQueries,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RunID,
		&i.CurrentStage,
		&i.Progress,
		&i.ErrorMessage,
	)
	return &i, err
}

const updateResearchTopicState = `-- name: UpdateResearchTopicState :one
UPDATE research_topics
SET status = $2,
    current_stage = $3,
    progress = $4,
    error_message = $5,
    updated_at = NOW(),
    completed_at = CASE
        WHEN $2 = 'completed' THEN COALESCE(completed_at, NOW())
        ELSE completed_at
    END
WHERE id = $1
RETURNING id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message
`

type UpdateResearchTopicStateParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	CurrentStage string      `json:"current_stage"`
	Progress     float64     `json:"progress"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateResearchTopicState(ctx context.Context, arg UpdateResearchTopicStateParams) (*ResearchTopic, error) {
	row := q.db.QueryRow(ctx, updateResearchTopicState,
		arg.ID,
		arg.Status,
		arg.CurrentStage,
		arg.Progress,
		arg.ErrorMessage,
	)
	var i ResearchTopic
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ExpandedQueries,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RunID,
		&i.CurrentStage,
		&i.Progress,
		&i.ErrorMessage,
	)
	return &i, err
}

const updateResearchTopicStatus = `-- name: UpdateResearchTopicStatus :one
UPDATE research_topics 
SET status = $2, updated_at = NOW(), completed_at = COALESCE($3, completed_at)
WHERE id = $1
RETURNING id, topic, expanded_queries, status, config, created_at, updated_at, completed_at, run_id, current_stage, progress, error_message
`

type UpdateResearchTopicStatusParams struct {
	ID          uuid.UUID          `json:"id"`
	Status      string             `json:"status"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateResearchTopicStatus(ctx context.Context, arg UpdateResearchTopicStatusParams) (*ResearchTopic, error) {
	row := q.db.QueryRow(ctx, updateResearchTopicStatus, arg.ID, arg.Status, arg.CompletedAt)
	var i ResearchTopic
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.ExpandedQueries,
		&i.Status,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RunID,
		&i.CurrentStage,
		&i.Progress,
		&i.ErrorMessage,
	)
	return &i, err
}

const upsertAuthorByName = `-- name: UpsertAuthorByName :one
INSERT INTO authors (name)
VALUES ($1)
ON CONFLICT (lower(btrim(name))) WHERE semantic_scholar_id IS NULL DO UPDATE SET
    name = EXCLUDED.name
RETURNING id, name, semantic_scholar_id, orcid, created_at
`

func (q *Queries) UpsertAuthorByName(ctx context.Context, name string) (*Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthorByName, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SemanticScholarID,
		&i.Orcid,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertAuthorBySemanticScholarID = `-- name: UpsertAuthorBySemanticScholarID :one
INSERT INTO authors (name, semantic_scholar_id)
VALUES ($1, $2)
ON CONFLICT (semantic_scholar_id) WHERE semantic_scholar_id IS NOT NULL DO UPDATE SET
    name = EXCLUDED.name
RETURNING id, name, semantic_scholar_id, orcid, created_at
`

type UpsertAuthorBySemanticScholarIDParams struct {
	Name              string      `json:"name"`
	SemanticScholarID pgtype.Text `json:"semantic_scholar_id"`
}

func (q *Queries) UpsertAuthorBySemanticScholarID(ctx context.Context, arg UpsertAuthorBySemanticScholarIDParams) (*Author, error) {
	row := q.db.QueryRow(ctx, upsertAuthorBySemanticScholarID, arg.Name, arg.SemanticScholarID)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SemanticScholarID,
		&i.Orcid,
		&i.CreatedAt,
	)
	return &i, err
}

const upsertPaperChunk = `-- name: UpsertPaperChunk :one
INSERT INTO paper_chunks (
    topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source,
    embedding_status, error_message
)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending', NULL)
ON CONFLICT (topic_id, paper_id, chunk_type, chunk_index) DO UPDATE SET
    text = EXCLUDED.text,
    content_hash = EXCLUDED.content_hash,
    source = EXCLUDED.source,
    embedding_status = CASE
        WHEN paper_chunks.content_hash = EXCLUDED.content_hash THEN paper_chunks.embedding_status
        ELSE 'pending'
    END,
    error_message = CASE
        WHEN paper_chunks.content_hash = EXCLUDED.content_hash THEN paper_chunks.error_message
        ELSE NULL
    END,
    updated_at = NOW()
RETURNING id, topic_id, paper_id, chunk_type, chunk_index, text, content_hash, source, embedding_status, error_message, created_at, updated_at
`

type UpsertPaperChunkParams struct {
	TopicID     uuid.UUID `json:"topic_id"`
	PaperID     uuid.UUID `json:"paper_id"`
	ChunkType   string    `json:"chunk_type"`
	ChunkIndex  int32     `json:"chunk_index"`
	Text        string    `json:"text"`
	ContentHash string    `json:"content_hash"`
	Source      string    `json:"source"`
}

func (q *Queries) UpsertPaperChunk(ctx context.Context, arg UpsertPaperChunkParams) (*PaperChunk, error) {
	row := q.db.QueryRow(ctx, upsertPaperChunk,
		arg.TopicID,
		arg.PaperID,
		arg.ChunkType,
		arg.ChunkIndex,
		arg.Text,
		arg.ContentHash,
		arg.Source,
	)
	var i PaperChunk
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.PaperID,
		&i.ChunkType,
		&i.ChunkIndex,
		&i.Text,
		&i.ContentHash,
		&i.Source,
		&i.EmbeddingStatus,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
